apply from: "../publish.gradle"
dependencies {
    implementation project(":SevenZip")
    implementation libs.zip4j
    implementation libs.gradle
    implementation libs.commons.io
}
ext {
    artId = POM_ARTIFACT_ID
    versionName = rootProject.ext.versionName
    groupID = rootProject.ext.groupID
}