apply plugin: "groovy"
apply from: "../publish.gradle"
dependencies {
    implementation gradleApi()
    implementation localGroovy()
    implementation project(":AndResGuard-core")
}
ext {
    artId = POM_ARTIFACT_ID
    versionName = rootProject.ext.versionName
    groupID = rootProject.ext.groupID
}